### ISSUE TITLE
Refactoring point #1

### ISSUE THREAD

**Issue by guylev38** [guylev38/audioglyph#13]
After completing the open directory feature #12, the code seriously needs to be cleaned up and refactored before implementing the Audio Player #10 .

### Tasks

- [x]  Split the code into header files and ensure compilation.
- [x] Clean up the code, move to best practices.
- [x] Optimize where possible.
